modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="screwyourmobs"
version="4.0"
displayName="ScrewYourMobs!"
displayURL="https://modrinth.com/user/vinntekk"
logoFile="logo.png"
authors="vinntekk"
description="Remove any mob, anywhere, with simple JSON rules. Filter by ID or tag, per-dimension, global or per-world. Built-in editor, debug tools, and typo detection! Type '/sym' in chat to start."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.screwyourmobs]]
modId="neoforge"
type="required"
versionRange="[21.1.100,)"
ordering="NONE"
side="BOTH"

[[dependencies.screwyourmobs]]
modId="minecraft"
type="required"
versionRange="[1.21.1,]"
ordering="NONE"
side="BOTH"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration